services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/podcast_muse.db:/app/podcast_muse.db
    command: python simple-main.py
    restart: unless-stopped
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./podcast_muse.db