services:
  # Backend Service
  backend:
    container_name: podcast_muse_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./podcast_muse.db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/podcast_muse.db:/app/podcast_muse.db
    command: python simple-main.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    container_name: podcast_muse_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    command: npm run dev

networks:
  default:
    name: podcast_muse_dev