[build]
builder = "nixpacks"

# Backend Service - Python Flask
[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[variables]
PORT = "8000"
ENVIRONMENT = "production"
DATABASE_URL = "${{postgresql.DATABASE_URL}}"

# PostgreSQL Database
[postgresql]