[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "backend"
source = "backend"
[services.variables]
PORT = "8000"
ENVIRONMENT = "production"
DATABASE_URL = "${{postgresql.DATABASE_URL}}"

[[services]]
name = "frontend"
source = "frontend"
[services.variables]
PORT = "3000"
NEXT_PUBLIC_API_URL = "${{services.backend.url}}"
ENVIRONMENT = "production"

[postgresql]