[build]
builder = "nixpacks"

[deploy]
startCommand = "python flask-main.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[variables]
PORT = "8000"
ENVIRONMENT = "production"
DATABASE_URL = "${{postgresql.DATABASE_URL}}"

[postgresql]